@baseUrl = http://localhost:1337

### GET PROFILE - Con token valido (esegui prima auth-login.http)
# Importante: Prima esegui una richiesta in auth-login.http marcata con # @name login
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{login.response.body.accessToken}}

### GET PROFILE - Token manuale (sostituisci con il tuo token)
# @name profileWithToken
GET {{baseUrl}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTc0NjU3MSwiZXhwIjoxNzYxNzUwMTcxfQ.rVplk99YFnytyIfcM-G-oTIAUH0ksIiwkGUyzclpYtM

### GET PROFILE - Senza token (Atteso: 401 Unauthorized)
# @name profileNoAuth
GET {{baseUrl}}/auth/profile

### GET PROFILE - Token malformato (Atteso: 401 Unauthorized)
# @name profileInvalidToken
GET {{baseUrl}}/auth/profile
Authorization: Bearer invalid.token.here

### GET PROFILE - Token scaduto (Atteso: 401 Unauthorized)
# @name profileExpiredToken
GET {{baseUrl}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNjAwMDAwMDAwLCJleHAiOjE2MDAwMDM2MDB9.expired

### GET PROFILE - Bearer keyword mancante (Atteso: 401 Unauthorized)
# @name profileNoBearerKeyword
GET {{baseUrl}}/auth/profile
Authorization: YOUR_JWT_TOKEN_HERE

### GET PROFILE - Header Authorization vuoto (Atteso: 401 Unauthorized)
# @name profileEmptyAuth
GET {{baseUrl}}/auth/profile
Authorization: Bearer
